paritytech/governance-ui

- package.json
- src/app.tsx
- src/index.tsx
- yarn.lock
These changes:
- moves the App out of index to a separate module
- adds some packages for polkadot-wallet.
- some linting that my prettier made to make quoting consistent! I will add eslint and a full linter in a separate PR, but since this was already made I let it be. Let me know if we want to use another style.
> Move app to a separate module and add wallet dependencies

- src/components/connect.tsx
- src/components/wallet.tsx
- src/contexts/Account.tsx
- src/contexts/Wallets.tsx
Adds type for Account and Wallet context.
> add types for account and wallet contexts

- src/app.tsx
- src/components/voting.tsx
- src/contexts/Api.tsx
- src/index.tsx
> add simple conviction-voting

- .github/workflows/ci.yml
- package.json
- src/contexts/Wallets.tsx
Added simple CI action. Updated `lint` and `format` yarn scripts to make them more consistent.
> Added CI action

- assets/main.css
- assets/referenda.module.css
- package.json
- src/app.tsx
- src/components/common/card.tsx
- src/components/referenda.tsx
- src/components/voting.tsx
- src/contexts/Wallets.tsx
- yarn.lock
Note that I experimented with https://parceljs.org/languages/css/#css-modules and it looks like it fit our needs w/o the need to have an extra dependency.
> Moved to react-spring

- .eslintrc.json
- src/app.tsx
- src/chain/referenda.ts
- src/components/account.tsx
- src/components/common/card.tsx
- src/components/common/modal.tsx
- src/components/connect.tsx
- src/components/error-boundary.tsx
- src/components/referenda.tsx
- src/components/voting.tsx
- src/contexts/Api.tsx
- src/contexts/Wallets.tsx
- src/types.ts
These are some manual fixes to address the issues raised by eslint.
> Address eslint issues

- src/components/common/card.tsx
- src/components/notificationBox.module.css
- src/components/notificationBox.tsx
- src/contexts/Api.tsx
- src/contexts/Notification.tsx
- src/index.tsx
This adds a notification context and a notification box.
Currently it used shows a transient notification when the API connected, but we should be able to extend the functionality to add different errors there as well.
> add notification context and box

- package.json
- yarn.lock
> upgrade polkadot-onboard(fixes treeshaking)

- .github/workflows/playwright-e2e.yml
native performance and reliability was better than zombienet
more info re benchmark here #115
> clean up the e2e workflow

- package.json
- yarn.lock
Reverts paritytech/governance-ui#211
> Revert "Bump buffer from 5.5.0 to 6.0.3"

- assets/data/polkadot/delegates.json
> add staker space 

- src/App.tsx
- src/ui/components/Header.tsx
- src/ui/components/Headline.tsx
- src/ui/components/delegation/TrackSelect.tsx
- src/ui/components/delegation/delegateModal/Delegate.tsx
- src/ui/components/delegation/delegateModal/Undelegate.tsx
- src/ui/layouts/Delegation.tsx
- src/ui/lib/Modal.tsx
- tailwind.config.cjs
according to https://docs.google.com/document/d/13enJZ6fx2Q8u8y2nxWpt9g2oiogMbs48hX9Mw2lLPFU/edit?usp=sharing
> copy updated

- src/ui/components/NotificationBox.tsx
- tailwind.config.cjs
re: https://github.com/paritytech/governance-ui/issues/277
> snack bar prettified

- src/lifecycle/index.tsx
- src/lifecycle/types.ts
- src/ui/components/NotificationBox.tsx
- src/ui/components/delegation/DelegateCard.tsx
- src/ui/components/delegation/delegateModal/Delegate.tsx
- src/ui/components/delegation/delegateModal/Undelegate.tsx
- src/ui/lib/Button.tsx
> add notifications for tx call state and disable actions while processing the tx

- src/hooks/EscapeHandler.tsx
- src/ui/components/EllipsisTextbox.tsx
- src/ui/components/delegation/DelegateCard.tsx
- src/ui/lib/Modal.tsx
- src/ui/lib/types.tsx
-stop click event propagaton on button clicks
-close modals on scape
> fix modals

- src/contexts/Delegation.tsx
- src/contexts/Wallets.tsx
- src/lifecycle/index.tsx
- src/ui/components/delegation/DelegateCard.tsx
- src/ui/components/delegation/TrackSelect.tsx
- src/ui/components/delegation/delegateModal/Delegate.tsx
- src/ui/lib/Button.tsx
- yarn.lock
> unselect tracks after delegation and disable actions during tx

- src/ui/components/EllipsisTextbox.tsx
- src/ui/components/Header.tsx
- src/ui/components/delegation/DelegateCard.tsx
- src/ui/components/delegation/delegateModal/TxnModal.tsx
- src/ui/layouts/Delegation/DelegationLayout.tsx
- src/ui/layouts/Delegation/SelectedDelegate.tsx
To do: When arriving to SelectedDelegatePanel from clicking on a delegate card (as opposed to following a link a friend sent you), we should switch the logo in the header to a 'back' btn
> Delegate page fix

- src/lifecycle/index.tsx
- src/ui/components/delegation/delegateModal/TxnModal.tsx
- src/ui/components/delegation/delegateModal/Undelegate.tsx
> Improved metrics support

- src/ui/components/DelegatesBar.tsx
- src/ui/components/delegation/DelegateSection.tsx
- src/ui/components/delegation/TrackSelect.tsx
- src/ui/layouts/Delegation/DelegationPanel.tsx
Reverts paritytech/governance-ui#533
> Revert "Small fixes"

- assets/data/kusama/delegates.json
- assets/data/polkadot/delegates.json
Hello,
this PR will add Polkadotters as one of the delegates for OpenGov.
> Add Polkadotters to delegate registry

- assets/data/kusama/delegates.json
- assets/data/polkadot/delegates.json
Two changes are made within this PR:
- We have edited our polkadot profile
- We have added our kusama proflie
> Staker Space

- .dockerignore
- .github/workflows/ci.yml
- Dockerfile
- README.md
- assets/data/kusama/delegates.json
- scripts/build-container.sh
- yarn.lock
This can be test with an image I built:
```
podman run --name delegation-dashboard --rm -it -p 8080:80 docker.io/chevdor/polkadot-delegation-dashboard  
open http://localhost:8080/
```
> Add container image

- assets/data/polkadot/delegates.json
Hey guys! Just would like to register myself with this PR. Thanks.
> Add Dom as Polkadot Delegate

- assets/data/polkadot/delegates.json
Update to my last PR regarding the addition of Gaius_Sama as a Polkadot delegate following the recent merger of another delegate.
> Add Gaius_Sama as Polkadot Delegate

- src/contexts/Account.tsx
- src/utils/polkadot-api.ts
> fix invalid account imports

- assets/data/polkadot/delegates.json
> Added Birdo

- assets/data/polkadot/delegates.json
Added blockseeker.io as a delegate option
> Introduce blockseeker into delegates.json

- assets/data/polkadot/delegates.json
Just adding Ivy to the `delegates.json` file. 
Cheers
> Adding Ivy to delegates.json.

- assets/data/polkadot/delegates.json
Please consider adding Zooper Corp a long time 1kv validator to the list of open gov delegation
> Added Zooper Corp 1KV Validator to delegators
